### ISSUE TITLE
Received invalid agreement during negotiation phase

### ISSUE THREAD

**Issue by riebeb** [International-Data-Spaces-Association/IDS-Deployment-Examples#30]
Hello,

i have updated my IDS folder with the recent version,
i am trying the provider-consumer example.
Now i am not able to conclude the readme path, that was working before.

In the readme you are told to copy/paste the “permission” part and to change/add the “artifact ID”.
Somehow the “rule ID” was fix before it seems, because as already said I was able to get to the end with the lower 5.x version.

Now after the update, the “rule ID” is not correct and needs also to be replaced.

But now the issue is : “Received invalid agreement during negotiation phase.”

I double checked the IDs of all components by looking at the output of “create_resource.sh” and rechecking it in swagger.
They are all correct, nothing has been changed in the git clone. 

What can I do?

**Comment by sebplorenz** [comment]
Hi, I've updated the example with a postman collection. Pull request can be found here: https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/pull/32
Hope this helps.

**Comment by riebeb** [comment]
is this the same you have send me some weeks ago? i will give it a try, still removing the readme

**Comment by sebplorenz** [comment]
Hi @riebeb , I now also deleted the create_resource.sh from the repository. Do not use it for creating resources when using the postman collection.
The resources will be created during the startup of the provider connector. They are bootstrapped using the catalog.jsonld file.

It might lead to errors if you still use the create_resource.sh script.

**Comment by tanchy82** [comment]
> 

Hi, @[sebplorenz](https://github.com/sebplorenz), I never use create_resource.sh , start provider and consumer normal, and the offer can be checked by provider. But now hava a exception, consumer baunch negotiate a contract request, ‘ Error: response status is 500’  and  response body is 'Message handling or processing failed.'

**Comment by SebastianOpriel** [comment]
Hi @tanchy82 could you please provide more details on this issue?
I used @sebplorenz PR (https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/pull/32) and ran docker-compose without problems. Afterwards I used his postman collection and executed every call again without any problems.
