### ISSUE TITLE
Examples are outdated

### ISSUE THREAD

**Issue by syats** [International-Data-Spaces-Association/IDS-Deployment-Examples#9]
As per the readme, after deploying the "full example", I try to access

> Dataspace Connector Swagger UI: https://localhost:8080/api/docs

And I am getting back a 404. In general all endpoints in /api/ give back a 404.
Could you please advise?

**Comment by tmberthold** [comment]
Hello and thank you for the message!

Could you maybe briefly try the following URL?
https://localhost:8080/admin/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

**Comment by syats** [comment]
Thank you @tmberthold  for the prompt answer. 

Yes, this endpoint returns with a request for a basic auth header. 

I can't seem to find in the env file or the json-ld any reference to credentials other than the one for postgres. 
I see from the documentation of the Dataspace Connector that these credentials are set in the properties file. Is this modifiable with env variables? or what are the default credentials?

Thanks

**Comment by tmberthold** [comment]
Hello and good to hear we were able to help quickly!

The default settings can also be changed by env-variables, here are the default values and the properties names:
spring.security.user.name=admin
spring.security.user.password=password

**Comment by syats** [comment]
Thanks a lot!
